16012024-1932

diff --git a/tools/githooks/pre-commit b/tools/githooks/pre-commit
--- a/tools/githooks/pre-commit
+++ b/tools/githooks/pre-commit
@@ -3,15 +3,25 @@
 STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g')
 
 echo "Running check_jenkinsfiles.sh..."
-ls tools/githooks_scripts
 tools/githooks_scripts/check_jenkinsfiles.sh
 JENKINSFILE_CHECK_EXIT_CODE=$?
 
 if [ $JENKINSFILE_CHECK_EXIT_CODE -ne 0 ]; then
-    echo "Jenkinsfile check failed."
+    echo "[ERROR] Jenkinsfile check failed."
     exit 1
 else
-    echo "Jenkinsfile check succeeded."
+    echo "[INFO] Jenkinsfile check succeeded."
+fi
+
+echo "Running lint_python.sh..."
+tools/githooks_scripts/lint_python.sh
+PYTHON_LINTING_EXIT_CODE=$?
+
+if [ $PYTHON_LINTING_EXIT_CODE -ne 0 ]; then
+    echo "[ERROR] Python code linting failed."
+    exit 1
+else
+    echo "[INFO] Python code linting succeeded."
 fi
 
 git add -f "$STAGED_FILES"
